require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Naming/FileName:
  Exclude:
    - Gemfile
    - Guardfile
    - rspec-hive.gemspec

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 30

RSpec/DescribeClass:
  Exclude:
    - spec/lib/rspec/hive/matchers_spec.rb

Style/Encoding:
  Exclude:
    - 'rspec-hive.gemspec'
